version: '2.2'
services:
  postgres:
    image: "postgres:15"
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./pg_hba.conf:/var/lib/foo/pg_hba.conf
      - postgres-data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "hba_file=/var/lib/foo/pg_hba.conf" ]
    restart: always
    networks:
      - app
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    expose:
      - 9200
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app
    restart: on-failure
  kibana:
    container_name: kibana
    image: "kibana:7.4.0"
    restart: always
    environment:
      - ELASTICSEARCH_URIS=http://147.45.111.91:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app
  app:
    container_name: library
    build:
      context: .
      dockerfile: library.Dockerfile
    #    environment:
    #      ELASTICSEARCH_URIS: http://147.45.111.91:9200
    #      SPRING_DATASOURCE_URL: jdbc:postgresql://147.45.111.91:5432/postgres
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres-data:
