version: '3.8'
services:
  postgres:
    image: "postgres:15"
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5434
    ports:
      - "5434:5432"
    volumes:
      - ./pg_hba.conf:/var/lib/foo/pg_hba.conf
      - postgres-data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "hba_file=/var/lib/foo/pg_hba.conf" ]
    restart: always
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
  kibana:
    container_name: kibana
    image: "kibana:7.4.0"
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  app:
    container_name: library
    build:
      context: .
      dockerfile: library.Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5434/postgres?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure

volumes:
  postgres-data:
