version: '3.8'
services:
  postgres:
    image: "postgres:15"
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  liquibase-migrations:
    image: liquibase/liquibase:4.24.0
    depends_on:
      - postgres
    command:
      #      - --changeLogFile=changelog/master.xml
      - --changeLogFile=master.xml
      - --url=jdbc:postgresql://postgres:5432/postgres
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./src/main/resources/migrations/migrations/1.xml:/liquibase/changelog/master.xml
      - ./../../.m2/repository/org/postgresql/postgresql/42.2.18/postgresql-42.2.18.jar:/liquibase/internal/lib/postgresql-42.2.18.jar
    working_dir: /liquibase/changelog

  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

volumes:
  postgres-data:
