server:
  port: 8080

app:
  scripts:
    file:
      python: "C:/ProgramData/anaconda3/python.exe"
      path: "D:/study/digital-library-backend/temp.txt"
    find: "D:/study/digital-library-backend/src/main/resources/get_books.py"
    add: "D:/study/digital-library-backend/src/main/resources/add_book_to_index.py"
  books:
    number: 10
  words:
    weight:
      base: 1000
      extended: 1

spring:
  security:
    user:
      #      login: user by default
      password: chucha
      name: chucha

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://147.45.111.91:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:migrations/master.xml
    contexts: schema, data
  elasticsearch:
    uris: http://localhost:9200
    socket-timeout: 10s
    username: user
    password: secret

